### ISSUE TITLE
Please specify a license

### ISSUE THREAD

**Issue by loadhigh** [miyucy/brotli#13]
The repo is missing a LICENSE file with by default means the code is proprietary and all rights reserved.

**Comment by miyucy** [comment]
ah, I'm so sorry.
but, I'm do not familiar about software license.
Can I apply as public domain, MIT (or something) to this repo. please advice me if you can.

**Comment by loadhigh** [comment]
Using an existing license template makes things easier. Even if you declare your software to be public domain, without any legal disclaimer like in the MIT license, you can still be liable for damage. You can just copy the text from https://choosealicense.com/licenses/mit/ to LICENSE and update the rubygem file

**Comment by miyucy** [comment]
Thanks for advice. v0.1.6 will ship soon.
