### ISSUE TITLE
"ORIG_SRCS = buffer.c brotli.c" May be in Makefile instead of "ORIG_SRCS = brotli.c buffer.c"

### ISSUE THREAD

**Issue by loadhigh** [miyucy/brotli#17]
This causes the shared object to be built without any of the brotli code, causing error during run time

**Comment by miyucy** [comment]
Maybe fixes with this PR. https://github.com/miyucy/brotli/pull/16
Could you try with [v0.1.7](https://rubygems.org/gems/brotli/versions/0.1.7)?

**Comment by loadhigh** [comment]
Confirmed working.
