### ISSUE TITLE
Release 0.1.7 on rubygems

### ISSUE THREAD

**Issue by matthias-geier** [miyucy/brotli#19]
Noticed you have bumped the version to 0.1.7 but it's not on rubygems yet. Can you push it up there? Thanks!

**Comment by miyucy** [comment]
ah, really? I'll check it.

**Comment by miyucy** [comment]
I'm so sorry. I forgot to push git tag... 
I just pushed it. please check it https://rubygems.org/gems/brotli/versions/0.1.7

**Comment by olleolleolle** [comment]
@matthias-geier Is this issue resolved? https://rubygems.org/gems/brotli lists 0.1.7.

**Comment by matthias-geier** [comment]
@olleolleolle Yes, it has been resolved
