### ISSUE TITLE
Upgrade brotli to 1.0.0

### ISSUE THREAD

**Issue by thedrow** [miyucy/brotli#4]
When brotli upgrades to 1.0.0 we should upgrade as well.
See https://github.com/google/brotli/issues/483

**Comment by miyucy** [comment]
Thanks for information. I'll.

**Comment by gfx** [comment]
Now brotli v1.0.1 is released: https://github.com/google/brotli/releases

@miyucy do you have a plan to update this gem?

**Comment by miyucy** [comment]
Thanks for ping. I'm do not aware it was released.
I'm going to update gem with new brotli.


2017/10/18 18:45 "FUJI Goro" <notifications@github.com>:

**Comment by gfx** [comment]
Cool. Thanks!

**Comment by miyucy** [comment]
Just released.
https://rubygems.org/gems/brotli/versions/0.2.0
