### ISSUE TITLE
Allow `Brotli.inflate` to accept `StringIO`, beside just `String`

### ISSUE THREAD

**Issue by weshatheleopard** [miyucy/brotli#48]
When I have an object of type `StringIO`, I have to read it in first, and only then pass it to the gem. It would be nice to handle that _inside_ the gem.

At the very least, it would be something similar to:
```
def inflate(str_or_io)
  if str_or_io.is_a?(IO) then
    Brotli.inflate(str_or_io.read)
  else
    Brotli.inflate(str_or_io)
  end
end
```
can be done until proper stream reader is implemented in the C library.

**Comment by miyucy** [comment]
I appreciate your suggestion. It's very reasonable. I'll implement this.

**Comment by weshatheleopard** [comment]
Now when this is fixed, can you please update it on RubyGems?

**Comment by miyucy** [comment]
@weshatheleopard I apologize for the late response. I've just published a new version. If you encounter any issues with the update or have any questions, please don't hesitate to open an issue on the project's repository. I appreciate your patience and support.
